### ISSUE TITLE
could not determine kind of name for C.EVENT_WEAK_HASH_* errors

### ISSUE THREAD

**Issue by allabert** [fireeye/gocrack#42] opened 2018-03-19 09:20 UTC
Building fails with following errors. What i am missing here?
------------------------------------------------------------------------------------------------------------------------------
make build
mkdir -p builds/
go build -tags """" -o builds/linux/amd64/gocrack_worker  -ldflags \
        "-X github.com/fireeye/gocrack/worker.CompileRev=dc14ad5 \
         -X github.com/fireeye/gocrack/worker.CompileTime=1521450941 \
         -X github.com/fireeye/gocrack/worker/engines/hashcat.HashcatVersion=" \
        cmd/gocrack_worker/*.go
 github.com/fireeye/gocrack/gocat
gocat/gocat.go:287:7: could not determine kind of name for C.EVENT_WEAK_HASH_ALL_CRACKED
gocat/gocat.go:231:7: could not determine kind of name for C.EVENT_WEAK_HASH_POST
gocat/gocat.go:229:7: could not determine kind of name for C.EVENT_WEAK_HASH_PRE
Makefile:14: recipe for target 'build' failed
make: *** [build] Error 2
#
--------------------------------------------------------------------------------------------------------------------------------

Regards,
Allabert

**Comment by tankbusta** [comment] 2018-03-19 16:45
What version of hashcat is installed locally? It looks like you're trying to build it with Hashcat 4 and unfortunately, it's not supported yet as they've changed some of the events. 

If this is the case, go back to 3.6.X or switch to an experimental branch of GoCrack ` feat/hc_4_support`

**Comment by allabert** [comment] 2018-04-05 05:30
Tried the experimental branch, got the following error:

make build
fatal: Not a git repository (or any of the parent directories): .git
mkdir -p builds/
go build -tags """" -o builds/linux/amd64/gocrack_worker  -ldflags \
        "-X github.com/fireeye/gocrack/worker.CompileRev= \
         -X github.com/fireeye/gocrack/worker.CompileTime=1522905935 \
         -X github.com/fireeye/gocrack/worker/engines/hashcat.HashcatVersion=" \
        cmd/gocrack_worker/*.go
github.com/fireeye/gocrack/gocat
gocat/handlers.go:93: cannot use ectx.msg_len (type _Ctype_ulong) as type _Ctype_int in argument to _Cfunc_GoStringN
gocat/validator.go:92: cannot use ectx.msg_len (type _Ctype_ulong) as type _Ctype_int in argument to _Cfunc_GoStringN
Makefile:14: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by tankbusta** [comment] 2018-05-02 03:44
Hi @allabert, at this time Hashcat 4 is not supported and I'm not sure when I'll get around to it. 

Please use v3.6.0 until it's supported. I'm going to close this because it's related/duplicate of #6

**Closed by tankbusta** 2018-05-02 03:44 UTC
